#!/usr/bin/env php
<?php

use Symfony\Component\Filesystem\Filesystem;

$vendorDir = dirname(__DIR__).'/vendor';
printf("%s\n", $vendorDir);


$pharPath = "${vendorDir}/phpstan/phpstan/phpstan.phar";
$extractPath = "${vendorDir}/phpstan/phpstan-src";

if (is_file($pharPath)) {
    require "${vendorDir}/autoload.php";

    (new Filesystem())
        ->remove($extractPath);

    $phar = new Phar($pharPath);
    $phar->extractTo($extractPath);
    print $extractPath;
}
