name: Run Rector

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, gettext, iconv, simplexml, zip, gd #optional
          ini-values: "post_max_size=256M" #optional

      - name: Checkout
        uses: actions/checkout@v2
      - name: Install App
        uses: php-actions/composer@v5
        with:
          php_version: '7.4'
          php_extensions: intl gettext iconv simplexml zip gd #optional
      - name: Run rector
        run: vendor/bin/rector process vendor/collectiveaccess/providence/app --dry-run -v
      - name: Check PHP Version
        run: php -v
